# This example will use spot instance type for all
# provisioned instances
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: generic
  annotations:
    kubernetes.io/description: "Nodepool for generic workloads"
spec:
  template:
    metadata:
      # Labels are arbitrary key-values that are applied to all nodes
      labels:
        Application: generic
        Environment: generic
        eks.amazonaws.com/nodegroup: generic
    spec:
      nodeClassRef:
        name: generic
      requirements:
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: [ "eu-west-1a" ]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["t", "m", "r", "c"]
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: Gt
          values: ["2"]
        - key: "karpenter.k8s.aws/instance-memory"
          operator: Gt
          values: ["4096"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
      # Karpenter provides the ability to specify a few additional Kubelet args.
      # These are all optional and provide support for additional customization and use cases.
      kubelet:
        maxPods: 110
        # Disruption section which describes the ways in which Karpenter can disrupt and replace Nodes
        evictionHard:
          memory.available: 5%
          nodefs.available: 5%
          nodefs.inodesFree: 5%
        evictionSoft:
          memory.available: 10%
          nodefs.available: 10%
          nodefs.inodesFree: 10%
        evictionMaxPodGracePeriod: 60
        evictionSoftGracePeriod:
          memory.available: 1m
          nodefs.available: 1m30s
          nodefs.inodesFree: 2m

  # Resource limits constrain the total size of the cluster.
  # Limits prevent Karpenter from creating new instances once the limit is exceeded.
  limits:
    cpu: "8"
    memory: 12Gi

  # Configuration in this section constrains how aggressive Karpenter can be with performing operations
  # like rolling Nodes due to them hitting their maximum lifetime (expiry) or scaling down nodes to reduce cluster cost
  disruption:
    # Describes which types of Nodes Karpenter should consider for consolidation
    # If using 'WhenUnderutilized', Karpenter will consider all nodes for consolidation and attempt to remove or replace Nodes when it discovers that the Node is underutilized and could be changed to reduce cost
    # If using `WhenEmpty`, Karpenter will only consider nodes for consolidation that contain no workload pods
    consolidationPolicy: WhenUnderutilized

    # The amount of time Karpenter should wait after discovering a consolidation decision
    # This value can currently only be set when the consolidationPolicy is 'WhenEmpty'
    # You can choose to disable consolidation entirely by setting the string value 'Never' here
    # consolidateAfter: 30s

    # The amount of time a Node can live on the cluster before being removed
    # Avoiding long-running Nodes helps to reduce security vulnerabilities as well as to reduce the chance of issues that can plague Nodes with long uptimes such as file fragmentation or memory leaks from system processes
    # You can choose to disable expiration entirely by setting the string value 'Never' here
    expireAfter: 720h


  # Priority given to the NodePool when the scheduler considers which NodePool
  # to select. Higher weights indicate higher priority when comparing NodePools.
  # Specifying no weight is equivalent to specifying a weight of 0.
  weight: 10
