name: Deploy Karpenter

on:
  workflow_call

jobs:
  helm-deploy:
    defaults:
      run:
        shell: bash
        working-directory: karpenter-controller/
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ vars.EKS_DEPLOY_ROLE }}
      - name: Configure AWS Credentials
        id: aws_creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: '${{ vars.EKS_DEPLOY_ROLE }}'
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
      - name: prepare helm install
        id: helm_upgrade
        run: |
          aws eks update-kubeconfig --name ${{ vars.EKS_CLUSTER_NAME }} --region ${{ vars.AWS_REGION }}
          echo "Begin upgrade/install"
          docker logout public.ecr.aws
          helm upgrade --install karpenter oci://public.ecr.aws/karpenter/karpenter \
          --namespace "karpenter" --create-namespace \
          --version "0.36.0" \
          -f values.yaml \
          --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"='${{ vars.KARPENTER_CONTROLLER_ROLE }}' \
          --set settings.clusterName=${{ vars.EKS_CLUSTER_NAME }} \
          --set settings.clusterEndpoint='${{ vars.EKS_CLUSTER_ENDPOINT }}' \
          --set settings.interruptionQueue=${{ vars.KARPENTER_SQS }}
      - name: Replace env vars in yaml files
        run: |
          pwd
          cd karpenter-resources
          for i in `ls`; do
            envsubst < $i | sponge $i
          done
      - name: Deploy yaml files (if not deployed)
        run: |
          pwd
          cd karpenter-resources
          for i in `ls`; do
            echo "Updating $i"
            kubectl apply -f $i || echo Failed or is immutable: $i
          done
